### ISSUE TITLE
Context seems wrong for python

### ISSUE THREAD

**Issue by hanspinckaers** [zsugabubus/vim-paperplane#2]
Hi there,

Thanks for making this plugin. I encountered this issue:

![Screenshot from 2020-05-18 20-40-58](https://user-images.githubusercontent.com/70747/82248421-663a1900-9948-11ea-9ec0-83690d9591a8.png)

The context here is wrong, it should be like in vim-context (without the blank line):
![Screenshot from 2020-05-18 20-43-43](https://user-images.githubusercontent.com/70747/82248445-70f4ae00-9948-11ea-9b61-1f40fda7fe30.png)

**Comment by zsugabubus** [comment]
Thanks for the report.

**Comment by hanspinckaers** [comment]
Awesome thanks!
