### ISSUE TITLE
Pasting while paperplane is active hangs neovim

### ISSUE THREAD

**Issue by hanspinckaers** [zsugabubus/vim-paperplane#3]
First of all thanks for the work, it's a nice speedy plugin.

However, I cannot seem to paste anymore with paperplane active. It looks a bit like it gets into an infinite loop. I have to close my terminal window.

Cheers,
Hans

**Comment by zsugabubus** [comment]
Errrr. Sorry for the inconveniences.

Could you help me out with some test files?

**Comment by hanspinckaers** [comment]
I tested it out a bit more. It  seems to happen if I paste something with a colon at the end:

I started with an empty file (test.py) and tried to paste:
```
def test_func():
    pass
```

This works (but is invalid syntax):
```
def test_func()
    pass
```
