### ISSUE TITLE
Hang when changing function name

### ISSUE THREAD

**Issue by hanspinckaers** [zsugabubus/vim-paperplane#4]
Hi there,

Sorry for all the bug reports. This time it hangs with this dummy file:
```
def test():
    if not _:
        for i in range(_):
            pass

    del _
```

When I try to change the name of function ```test```  to ```_``` it hangs on InsertLeave.

Cheers,
Hans

**Comment by zsugabubus** [comment]
I cannot reproduce this. Tried resizing window but nothing.

What do you mean my hanging? High CPU usage?

**Comment by hanspinckaers** [comment]
That is a pity, I mean total freeze. Have to quit terminal.

**Comment by hanspinckaers** [comment]
I will try reproducing it later today

**Comment by zsugabubus** [comment]
In the most cases you can use <kbd>CTRL-C</kbd>. It should interrupt any in-progress commands.

> I mean total freeze. Have to quit terminal.

My plugin maybe sh1t, but a terminal freeze? I think (at least I hope) my plugin is not capable of such things.

**Comment by hanspinckaers** [comment]
Yeah, it surprised me too. However, didn't experience this today. Will close the issue!
